# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: create_publish_release_package

on: workflow_dispatch

jobs:
  release:

    runs-on: windows-latest

    permissions:
      packages: write
      contents: write
      repository-projects: write

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: create
      run: dotnet pack --configuration Release
      working-directory: PowerCollections
      
    - name: publish
      run: dotnet nuget push ".\PowerCollections\bin\Release\lleprechaun.PowerCollection.*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/lleprechaun/index.json" --skip-duplicate
      working-directory: PowerCollections
      
    - name: get xml
      id: xml
      uses: mavrosxristoforos/get-xml-info@1.1.1
      with:
        xml-file: 'PowerCollections\PowerCollections\PowerCollections.csproj'
        xpath: '//Version'

    - name: release
      uses: ncipollo/release-action@v1.12.0
      with:
        tag: 'v${{ steps.xml.outputs.info }}'
        token:  ${{ secrets.GITHUB_TOKEN }} 
        artifacts: 'PowerCollections\PowerCollections\bin\Release\lleprechaun.PowerCollections.${{ steps.xml.outputs.info }}.nupkg'
